import { ContactMeta } from 'src/app/models/common/contact-meta.model';

export const ContactMetaSG: ContactMeta = {
  salutation: [
    { label: '', value: '' },
    { value: 'Mr', label: 'Mr' },
    { value: 'Ms', label: 'Ms' },
    { value: 'Mrs', label: 'Mrs' },
    { value: 'Mdm', label: 'Mdm' },
    { value: 'Dr', label: 'Dr' },
    { value: 'Captain', label: 'Captain' },
    // tslint:disable-next-line: quotemark
    { value: "Dato'", label: "Dato'" },
    { value: 'Datin', label: 'Datin' },
    { value: 'Professor', label: 'Professor' },
    { value: 'Jus', label: 'Jus' },
  ],
  states: [],
  cities: [],
  genderList: [
    { label: '', value: '' },
    { value: 'Male', label: 'Male' },
    { value: 'Female', label: 'Female' },
  ],
  raceList: [
    { label: '', value: '' },
    { value: 'Chinese', label: 'Chinese' },
    { value: 'Malay', label: 'Malay' },
    { value: 'Indian', label: 'Indian' },
    { value: 'Boyanese', label: 'Boyanese' },
    { value: 'Caucasian', label: 'Caucasian' },
    { value: 'Ceylonese', label: 'Ceylonese' },
    { value: 'Eurasian', label: 'Eurasian' },
    { value: 'European', label: 'European' },
    { value: 'Filipino', label: 'Filipino' },
    { value: 'Japanese', label: 'Japanese' },
    { value: 'Korean', label: 'Korean' },
    { value: 'Others', label: 'Others' },
  ],
  docType: [
    { label: '', value: '' },
    {
      value: 'Singapore NRIC (e.g. S1234567D)',
      label: 'Singapore NRIC',
    },
    {
      value: 'Foreign Passport (e.g. 12345678)',
      label: 'Foreign Passport',
    },
    {
      value: 'Foreign Identification Number (e.g. F/G1234567N)',
      label: 'FIN',
    },
  ],
  defaultCountryCode: '65',
  countryCode: [
    { label: '65 (SG)', value: '65' },
    { label: '60 (MY)', value: '60' },
    { label: '376 (AD)', value: '376' },
    { label: '971 (AE)', value: '971' },
    { label: '93 (AF)', value: '93' },
    { label: '355 (AL)', value: '355' },
    { label: '374 (AM)', value: '374' },
    { label: '244 (AO)', value: '244' },
    { label: '54 (AR)', value: '54' },
    { label: '43 (AT)', value: '43' },
    { label: '61 (AU)', value: '61' },
    { label: '297 (AW)', value: '297' },
    { label: '994 (AZ)', value: '994' },
    { label: '387 (BA)', value: '387' },
    { label: '880 (BD)', value: '880' },
    { label: '32 (BE)', value: '32' },
    { label: '226 (BF)', value: '226' },
    { label: '359 (BG)', value: '359' },
    { label: '973 (BH)', value: '973' },
    { label: '257 (BI)', value: '257' },
    { label: '229 (BJ)', value: '229' },
    { label: '590 (BL)', value: '590' },
    { label: '673 (BN)', value: '673' },
    { label: '591 (BO)', value: '591' },
    { label: '599 (BQ)', value: '599' },
    { label: '55 (BR)', value: '55' },
    { label: '975 (BT)', value: '975' },
    { label: '267 (BW)', value: '267' },
    { label: '375 (BY)', value: '375' },
    { label: '501 (BZ)', value: '501' },
    { label: '1 (CA)', value: '1' },
    { label: '61 (CC)', value: '61' },
    { label: '243 (CD)', value: '243' },
    { label: '236 (CF)', value: '236' },
    { label: '242 (CG)', value: '242' },
    { label: '41 (CH)', value: '41' },
    { label: '225 (CI)', value: '225' },
    { label: '682 (CK)', value: '682' },
    { label: '56 (CL)', value: '56' },
    { label: '237 (CM)', value: '237' },
    { label: '86 (CN)', value: '86' },
    { label: '57 (CO)', value: '57' },
    { label: '506 (CR)', value: '506' },
    { label: '53 (CU)', value: '53' },
    { label: '238 (CV)', value: '238' },
    { label: '599 (CW)', value: '599' },
    { label: '61 (CX)', value: '61' },
    { label: '357 (CY)', value: '357' },
    { label: '420 (CZ)', value: '420' },
    { label: '49 (DE)', value: '49' },
    { label: '253 (DJ)', value: '253' },
    { label: '45 (DK)', value: '45' },
    { label: '213 (DZ)', value: '213' },
    { label: '593 (EC)', value: '593' },
    { label: '372 (EE)', value: '372' },
    { label: '20 (EG)', value: '20' },
    { label: '212 (EH)', value: '212' },
    { label: '291 (ER)', value: '291' },
    { label: '34 (ES)', value: '34' },
    { label: '251 (ET)', value: '251' },
    { label: '358 (FI)', value: '358' },
    { label: '679 (FJ)', value: '679' },
    { label: '500 (FK)', value: '500' },
    { label: '691 (FM)', value: '691' },
    { label: '298 (FO)', value: '298' },
    { label: '33 (FR)', value: '33' },
    { label: '241 (GA)', value: '241' },
    { label: '44 (GB)', value: '44' },
    { label: '995 (GE)', value: '995' },
    { label: '594 (GF)', value: '594' },
    { label: '233 (GH)', value: '233' },
    { label: '350 (GI)', value: '350' },
    { label: '299 (GL)', value: '299' },
    { label: '220 (GM)', value: '220' },
    { label: '224 (GN)', value: '224' },
    { label: '590 (GP)', value: '590' },
    { label: '240 (GQ)', value: '240' },
    { label: '30 (GR)', value: '30' },
    { label: '502 (GT)', value: '502' },
    { label: '245 (GW)', value: '245' },
    { label: '592 (GY)', value: '592' },
    { label: '852 (HK)', value: '852' },
    { label: '504 (HN)', value: '504' },
    { label: '385 (HR)', value: '385' },
    { label: '509 (HT)', value: '509' },
    { label: '36 (HU)', value: '36' },
    { label: '62 (ID)', value: '62' },
    { label: '353 (IE)', value: '353' },
    { label: '972 (IL)', value: '972' },
    { label: '91 (IN)', value: '91' },
    { label: '246 (IO)', value: '246' },
    { label: '964 (IQ)', value: '964' },
    { label: '98 (IR)', value: '98' },
    { label: '354 (IS)', value: '354' },
    { label: '39 (IT)', value: '39' },
    { label: '962 (JO)', value: '962' },
    { label: '81 (JP)', value: '81' },
    { label: '254 (KE)', value: '254' },
    { label: '996 (KG)', value: '996' },
    { label: '855 (KH)', value: '855' },
    { label: '686 (KI)', value: '686' },
    { label: '269 (KM)', value: '269' },
    { label: '850 (KP)', value: '850' },
    { label: '82 (KR)', value: '82' },
    { label: '965 (KW)', value: '965' },
    { label: '7 (KZ)', value: '7' },
    { label: '856 (LA)', value: '856' },
    { label: '961 (LB)', value: '961' },
    { label: '423 (LI)', value: '423' },
    { label: '94 (LK)', value: '94' },
    { label: '231 (LR)', value: '231' },
    { label: '266 (LS)', value: '266' },
    { label: '370 (LT)', value: '370' },
    { label: '352 (LU)', value: '352' },
    { label: '371 (LV)', value: '371' },
    { label: '218 (LY)', value: '218' },
    { label: '212 (MA)', value: '212' },
    { label: '377 (MC)', value: '377' },
    { label: '373 (MD)', value: '373' },
    { label: '382 (ME)', value: '382' },
    { label: '590 (MF)', value: '590' },
    { label: '261 (MG)', value: '261' },
    { label: '692 (MH)', value: '692' },
    { label: '389 (MK)', value: '389' },
    { label: '223 (ML)', value: '223' },
    { label: '95 (MM)', value: '95' },
    { label: '976 (MN)', value: '976' },
    { label: '853 (MO)', value: '853' },
    { label: '596 (MQ)', value: '596' },
    { label: '222 (MR)', value: '222' },
    { label: '356 (MT)', value: '356' },
    { label: '230 (MU)', value: '230' },
    { label: '960 (MV)', value: '960' },
    { label: '265 (MW)', value: '265' },
    { label: '52 (MX)', value: '52' },
    { label: '258 (MZ)', value: '258' },
    { label: '264 (NA)', value: '264' },
    { label: '687 (NC)', value: '687' },
    { label: '227 (NE)', value: '227' },
    { label: '672 (NF)', value: '672' },
    { label: '234 (NG)', value: '234' },
    { label: '505 (NI)', value: '505' },
    { label: '31 (NL)', value: '31' },
    { label: '47 (NO)', value: '47' },
    { label: '977 (NP)', value: '977' },
    { label: '674 (NR)', value: '674' },
    { label: '683 (NU)', value: '683' },
    { label: '64 (NZ)', value: '64' },
    { label: '968 (OM)', value: '968' },
    { label: '507 (PA)', value: '507' },
    { label: '51 (PE)', value: '51' },
    { label: '689 (PF)', value: '689' },
    { label: '675 (PG)', value: '675' },
    { label: '63 (PH)', value: '63' },
    { label: '92 (PK)', value: '92' },
    { label: '48 (PL)', value: '48' },
    { label: '508 (PM)', value: '508' },
    { label: '870 (PN)', value: '870' },
    { label: '970 (PS)', value: '970' },
    { label: '351 (PT)', value: '351' },
    { label: '680 (PW)', value: '680' },
    { label: '595 (PY)', value: '595' },
    { label: '974 (QA)', value: '974' },
    { label: '262 (RE)', value: '262' },
    { label: '40 (RO)', value: '40' },
    { label: '381 (RS)', value: '381' },
    { label: '7 (RU)', value: '7' },
    { label: '250 (RW)', value: '250' },
    { label: '966 (SA)', value: '966' },
    { label: '677 (SB)', value: '677' },
    { label: '248 (SC)', value: '248' },
    { label: '249 (SD)', value: '249' },
    { label: '46 (SE)', value: '46' },
    { label: '290 (SH)', value: '290' },
    { label: '386 (SI)', value: '386' },
    { label: '47 (SJ)', value: '47' },
    { label: '421 (SK)', value: '421' },
    { label: '232 (SL)', value: '232' },
    { label: '378 (SM)', value: '378' },
    { label: '221 (SN)', value: '221' },
    { label: '252 (SO)', value: '252' },
    { label: '597 (SR)', value: '597' },
    { label: '211 (SS)', value: '211' },
    { label: '239 (ST)', value: '239' },
    { label: '503 (SV)', value: '503' },
    { label: '599 (SX)', value: '599' },
    { label: '963 (SY)', value: '963' },
    { label: '268 (SZ)', value: '268' },
    { label: '235 (TD)', value: '235' },
    { label: '228 (TG)', value: '228' },
    { label: '66 (TH)', value: '66' },
    { label: '992 (TJ)', value: '992' },
    { label: '690 (TK)', value: '690' },
    { label: '670 (TL)', value: '670' },
    { label: '993 (TM)', value: '993' },
    { label: '216 (TN)', value: '216' },
    { label: '676 (TO)', value: '676' },
    { label: '90 (TR)', value: '90' },
    { label: '688 (TV)', value: '688' },
    { label: '886 (TW)', value: '886' },
    { label: '255 (TZ)', value: '255' },
    { label: '380 (UA)', value: '380' },
    { label: '256 (UG)', value: '256' },
    { label: '1 (UM)', value: '1' },
    { label: '598 (UY)', value: '598' },
    { label: '998 (UZ)', value: '998' },
    { label: '379 (VA)', value: '379' },
    { label: '58 (VE)', value: '58' },
    { label: '84 (VN)', value: '84' },
    { label: '678 (VU)', value: '678' },
    { label: '681 (WF)', value: '681' },
    { label: '685 (WS)', value: '685' },
    { label: '967 (YE)', value: '967' },
    { label: '262 (YT)', value: '262' },
    { label: '27 (ZA)', value: '27' },
    { label: '260 (ZM)', value: '260' },
    { label: '263 (ZW)', value: '263' },
  ],
  countryList: [
    { label: 'Singapore', value: 'Singapore' },
    { label: 'Malaysia', value: 'Malaysia' },
    { label: 'Afghanistan', value: 'Afghanistan' },
    { label: 'ALA Aland Islands', value: 'ALA Aland Islands' },
    { label: 'Albania', value: 'Albania' },
    { label: 'Algeria', value: 'Algeria' },
    { label: 'American Samoa', value: 'American Samoa' },
    { label: 'Andorra', value: 'Andorra' },
    { label: 'Angola', value: 'Angola' },
    { label: 'Anguilla', value: 'Anguilla' },
    { label: 'Antarctica', value: 'Antarctica' },
    { label: 'Antigua and Barbuda', value: 'Antigua and Barbuda' },
    { label: 'Argentina', value: 'Argentina' },
    { label: 'Armenia', value: 'Armenia' },
    { label: 'Aruba', value: 'Aruba' },
    { label: 'Australia', value: 'Australia' },
    { label: 'Austria', value: 'Austria' },
    { label: 'Azerbaijan', value: 'Azerbaijan' },
    { label: 'Bahamas', value: 'Bahamas' },
    { label: 'Bahrain', value: 'Bahrain' },
    { label: 'Bangladesh', value: 'Bangladesh' },
    { label: 'Barbados', value: 'Barbados' },
    { label: 'Belarus', value: 'Belarus' },
    { label: 'Belgium', value: 'Belgium' },
    { label: 'Belize', value: 'Belize' },
    { label: 'Benin', value: 'Benin' },
    { label: 'Bermuda', value: 'Bermuda' },
    { label: 'Bhutan', value: 'Bhutan' },
    { label: 'Bolivia', value: 'Bolivia' },
    { label: 'Bosnia and Herzegovina', value: 'Bosnia and Herzegovina' },
    { label: 'Botswana', value: 'Botswana' },
    { label: 'Bouvet Island', value: 'Bouvet Island' },
    { label: 'Brazil', value: 'Brazil' },
    {
      label: 'British Indian Ocean Territory',
      value: 'British Indian Ocean Territory',
    },
    { label: 'British Virgin Islands', value: 'British Virgin Islands' },
    { label: 'Brunei Darussalam', value: 'Brunei Darussalam' },
    { label: 'Bulgaria', value: 'Bulgaria' },
    { label: 'Burkina Faso', value: 'Burkina Faso' },
    { label: 'Burundi', value: 'Burundi' },
    { label: 'Cambodia', value: 'Cambodia' },
    { label: 'Cameroon', value: 'Cameroon' },
    { label: 'Canada', value: 'Canada' },
    { label: 'Cape Verde', value: 'Cape Verde' },
    { label: 'Cayman Islands', value: 'Cayman Islands' },
    { label: 'Central African Republic', value: 'Central African Republic' },
    { label: 'Chad', value: 'Chad' },
    { label: 'Chile', value: 'Chile' },
    { label: 'China', value: 'China' },
    { label: 'Christmas Island', value: 'Christmas Island' },
    { label: 'Cocos (Keeling) Islands', value: 'Cocos (Keeling) Islands' },
    { label: 'Colombia', value: 'Colombia' },
    { label: 'Comoros', value: 'Comoros' },
    { label: 'Congo (Brazzaville)', value: 'Congo (Brazzaville)' },
    { label: 'Congo, (Kinshasa)', value: 'Congo, (Kinshasa)' },
    { label: 'Cook Islands', value: 'Cook Islands' },
    { label: 'Costa Rica', value: 'Costa Rica' },
    // tslint:disable-next-line: quotemark
    { label: "Côte d'Ivoire", value: 'Côte dIvoire' },
    { label: 'Croatia', value: 'Croatia' },
    { label: 'Cuba', value: 'Cuba' },
    { label: 'Cyprus', value: 'Cyprus' },
    { label: 'Czech Republic', value: 'Czech Republic' },
    { label: 'Denmark', value: 'Denmark' },
    { label: 'Djibouti', value: 'Djibouti' },
    { label: 'Dominica', value: 'Dominica' },
    { label: 'Dominican Republic', value: 'Dominican Republic' },
    { label: 'Ecuador', value: 'Ecuador' },
    { label: 'Egypt', value: 'Egypt' },
    { label: 'El Salvador', value: 'El Salvador' },
    { label: 'Equatorial Guinea', value: 'Equatorial Guinea' },
    { label: 'Eritrea', value: 'Eritrea' },
    { label: 'Estonia', value: 'Estonia' },
    { label: 'Ethiopia', value: 'Ethiopia' },
    {
      label: 'Falkland Islands (Malvinas)',
      value: 'Falkland Islands (Malvinas)',
    },
    { label: 'Faroe Islands', value: 'Faroe Islands' },
    { label: 'Fiji', value: 'Fiji' },
    { label: 'Finland', value: 'Finland' },
    { label: 'France', value: 'France' },
    { label: 'French Guiana', value: 'French Guiana' },
    { label: 'French Polynesia', value: 'French Polynesia' },
    {
      label: 'French Southern territories',
      value: 'French Southern territories',
    },
    { label: 'Gabon', value: 'Gabon' },
    { label: 'Gambia', value: 'Gambia' },
    { label: 'Georgia', value: 'Georgia' },
    { label: 'Germany', value: 'Germany' },
    { label: 'Ghana', value: 'Ghana' },
    { label: 'Gibraltar', value: 'Gibraltar' },
    { label: 'Greece', value: 'Greece' },
    { label: 'Greenland', value: 'Greenland' },
    { label: 'Grenada', value: 'Grenada' },
    { label: 'Guadeloupe', value: 'Guadeloupe' },
    { label: 'Guam', value: 'Guam' },
    { label: 'Guatemala', value: 'Guatemala' },
    { label: 'Guernsey', value: 'Guernsey' },
    { label: 'Guinea', value: 'Guinea' },
    { label: 'Guinea-Bissau', value: 'Guinea-Bissau' },
    { label: 'Guyana', value: 'Guyana' },
    { label: 'Haiti', value: 'Haiti' },
    {
      label: 'Heard and Mcdonald Islands',
      value: 'Heard and Mcdonald Islands',
    },
    {
      label: 'Holy See (Vatican City State)',
      value: 'Holy See (Vatican City State)',
    },
    { label: 'Honduras', value: 'Honduras' },
    { label: 'Hong Kong, SAR China', value: 'Hong Kong, SAR China' },
    { label: 'Hungary', value: 'Hungary' },
    { label: 'Iceland', value: 'Iceland' },
    { label: 'India', value: 'India' },
    { label: 'Indonesia', value: 'Indonesia' },
    { label: 'Iran, Islamic Republic of', value: 'Iran, Islamic Republic of' },
    { label: 'Iraq', value: 'Iraq' },
    { label: 'Ireland', value: 'Ireland' },
    { label: 'Isle of Man', value: 'Isle of Man' },
    { label: 'Israel', value: 'Israel' },
    { label: 'Italy', value: 'Italy' },
    { label: 'Jamaica', value: 'Jamaica' },
    { label: 'Japan', value: 'Japan' },
    { label: 'JERSEY', value: 'JERSEY' },
    { label: 'Jordan', value: 'Jordan' },
    { label: 'Kazakhstan', value: 'Kazakhstan' },
    { label: 'Kenya', value: 'Kenya' },
    { label: 'Kiribati', value: 'Kiribati' },
    { label: 'Korea (North)', value: 'Korea (North)' },
    { label: 'Korea (South)', value: 'Korea (South)' },
    { label: 'Kuwait', value: 'Kuwait' },
    { label: 'Kyrgyzstan', value: 'Kyrgyzstan' },
    { label: 'Lao PDR', value: 'Lao PDR' },
    { label: 'Latvia', value: 'Latvia' },
    { label: 'Lebanon', value: 'Lebanon' },
    { label: 'Lesotho', value: 'Lesotho' },
    { label: 'Liberia', value: 'Liberia' },
    { label: 'Libya', value: 'Libya' },
    { label: 'Liechtenstein', value: 'Liechtenstein' },
    { label: 'Lithuania', value: 'Lithuania' },
    { label: 'Luxembourg', value: 'Luxembourg' },
    { label: 'Macao, SAR China', value: 'Macao, SAR China' },
    { label: 'Macedonia, Republic of', value: 'Macedonia, Republic of' },
    { label: 'Madagascar', value: 'Madagascar' },
    { label: 'Malawi', value: 'Malawi' },
    { label: 'Maldives', value: 'Maldives' },
    { label: 'Mali', value: 'Mali' },
    { label: 'Malta', value: 'Malta' },
    { label: 'Marshall Islands', value: 'Marshall Islands' },
    { label: 'Martinique', value: 'Martinique' },
    { label: 'Mauritania', value: 'Mauritania' },
    { label: 'Mauritius', value: 'Mauritius' },
    { label: 'Mayotte', value: 'Mayotte' },
    { label: 'Mexico', value: 'Mexico' },
    {
      label: 'Micronesia, Federated States of',
      value: 'Micronesia, Federated States of',
    },
    { label: 'Moldova', value: 'Moldova' },
    { label: 'Monaco', value: 'Monaco' },
    { label: 'Mongolia', value: 'Mongolia' },
    { label: 'Montenegro', value: 'Montenegro' },
    { label: 'Montserrat', value: 'Montserrat' },
    { label: 'Morocco', value: 'Morocco' },
    { label: 'Mozambique', value: 'Mozambique' },
    { label: 'Myanmar', value: 'Myanmar' },
    { label: 'Namibia', value: 'Namibia' },
    { label: 'Nauru', value: 'Nauru' },
    { label: 'Nepal', value: 'Nepal' },
    { label: 'Netherlands', value: 'Netherlands' },
    { label: 'Netherlands Antilles', value: 'Netherlands Antilles' },
    { label: 'New Caledonia', value: 'New Caledonia' },
    { label: 'New Zealand', value: 'New Zealand' },
    { label: 'Nicaragua', value: 'Nicaragua' },
    { label: 'Niger', value: 'Niger' },
    { label: 'Nigeria', value: 'Nigeria' },
    { label: 'Niue', value: 'Niue' },
    { label: 'Norfolk Island', value: 'Norfolk Island' },
    { label: 'Northern Mariana Islands', value: 'Northern Mariana Islands' },
    { label: 'Norway', value: 'Norway' },
    { label: 'Oman', value: 'Oman' },
    { label: 'Pakistan', value: 'Pakistan' },
    { label: 'Palau', value: 'Palau' },
    { label: 'Palestinian Territory', value: 'Palestinian Territory' },
    { label: 'Panama', value: 'Panama' },
    { label: 'Papua New Guinea', value: 'Papua New Guinea' },
    { label: 'Paraguay', value: 'Paraguay' },
    { label: 'Peru', value: 'Peru' },
    { label: 'Philippines', value: 'Philippines' },
    { label: 'Pitcairn', value: 'Pitcairn' },
    { label: 'Poland', value: 'Poland' },
    { label: 'Portugal', value: 'Portugal' },
    { label: 'Puerto Rico', value: 'Puerto Rico' },
    { label: 'Qatar', value: 'Qatar' },
    { label: 'Réunion', value: 'Réunion' },
    { label: 'Romania', value: 'Romania' },
    { label: 'Russian Federation', value: 'Russian Federation' },
    { label: 'Rwanda', value: 'Rwanda' },
    { label: 'Saint-Barthélemy', value: 'Saint-Barthélemy' },
    { label: 'Saint Helena', value: 'Saint Helena' },
    {
      label: 'Saint-Martin (French part)',
      value: 'Saint-Martin (French part)',
    },
    { label: 'Saint Kitts and Nevis', value: 'Saint Kitts and Nevis' },
    { label: 'Saint Lucia', value: 'Saint Lucia' },
    { label: 'Saint Pierre and Miquelon', value: 'Saint Pierre and Miquelon' },
    {
      label: 'Saint Vincent and Grenadines',
      value: 'Saint Vincent and Grenadines',
    },
    { label: 'Samoa', value: 'Samoa' },
    { label: 'San Marino', value: 'San Marino' },
    { label: 'Sao Tome and Principe', value: 'Sao Tome and Principe' },
    { label: 'Saudi Arabia', value: 'Saudi Arabia' },
    { label: 'Senegal', value: 'Senegal' },
    { label: 'Serbia', value: 'Serbia' },
    { label: 'Seychelles', value: 'Seychelles' },
    { label: 'Sierra Leone', value: 'Sierra Leone' },
    { label: 'Slovakia', value: 'Slovakia' },
    { label: 'Slovenia', value: 'Slovenia' },
    { label: 'Solomon Islands', value: 'Solomon Islands' },
    { label: 'Somalia', value: 'Somalia' },
    { label: 'South Africa', value: 'South Africa' },
    { label: 'South Georgia', value: 'South Georgia' },
    { label: 'South Sudan', value: 'South Sudan' },
    { label: 'Spain', value: 'Spain' },
    { label: 'Sri Lanka', value: 'Sri Lanka' },
    { label: 'Sudan', value: 'Sudan' },
    { label: 'Suriname', value: 'Suriname' },
    {
      label: 'Svalbard and Jan Mayen Islands',
      value: 'Svalbard and Jan Mayen Islands',
    },
    { label: 'Swaziland', value: 'Swaziland' },
    { label: 'Sweden', value: 'Sweden' },
    { label: 'Switzerland', value: 'Switzerland' },
    {
      label: 'Syrian Arab Republic (Syria)',
      value: 'Syrian Arab Republic (Syria)',
    },
    { label: 'Taiwan, Republic of China', value: 'Taiwan, Republic of China' },
    { label: 'Tajikistan', value: 'Tajikistan' },
    {
      label: 'Tanzania, United Republic of',
      value: 'Tanzania, United Republic of',
    },
    { label: 'Thailand', value: 'Thailand' },
    { label: 'Timor-Leste', value: 'Timor-Leste' },
    { label: 'Togo', value: 'Togo' },
    { label: 'Tokelau', value: 'Tokelau' },
    { label: 'Tonga', value: 'Tonga' },
    { label: 'Trinidad and Tobago', value: 'Trinidad and Tobago' },
    { label: 'Tunisia', value: 'Tunisia' },
    { label: 'Turkey', value: 'Turkey' },
    { label: 'Turkmenistan', value: 'Turkmenistan' },
    { label: 'Turks and Caicos Islands', value: 'Turks and Caicos Islands' },
    { label: 'Tuvalu', value: 'Tuvalu' },
    { label: 'Uganda', value: 'Uganda' },
    { label: 'Ukraine', value: 'Ukraine' },
    { label: 'United Arab Emirates', value: 'United Arab Emirates' },
    { label: 'United Kingdom', value: 'United Kingdom' },
    { label: 'United States of America', value: 'United States of America' },
    { label: 'Uruguay', value: 'Uruguay' },
    { label: 'US Minor Outlying Islands', value: 'US Minor Outlying Islands' },
    { label: 'Uzbekistan', value: 'Uzbekistan' },
    { label: 'Vanuatu', value: 'Vanuatu' },
    {
      label: 'Venezuela (Bolivarian Republic)',
      value: 'Venezuela (Bolivarian Republic)',
    },
    { label: 'Viet Nam', value: 'Viet Nam' },
    { label: 'Virgin Islands, US', value: 'Virgin Islands, US' },
    { label: 'Wallis and Futuna Islands', value: 'Wallis and Futuna Islands' },
    { label: 'Western Sahara', value: 'Western Sahara' },
    { label: 'Yemen', value: 'Yemen' },
    { label: 'Zambia', value: 'Zambia' },
    { label: 'Zimbabwe', value: 'Zimbabwe' },
  ],
};
